ikir        = ['non permafrost', 'sporadic', 'discontinuous', 'continuous']
kopp        = ["D.b", "D.c", "D.d", "ET"]
wetl        = ['wetland', 'bog', 'fen', 'marsh', 'permafrost_bog', 'tundra_wetland']
kaudet      = ['whole_year', "summer", "freezing", "winter"]
pripost     = ['pri', 'post']
luokittelut = ['ikir', 'köppen', 'wetland']
